version: "3.7"
services:
  main:
    image: golang:alpine
    volumes:
      - .:/app
    command: ["go", "run", "/app/main.go"]
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: xchange
    volumes: 
      - /var/lib/postgresql/data
      - ./docker/postgres.sh:/docker-entrypoint-initdb.d/postgres.sh
  