// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the account id and amount (could be negative to reduce).
type ChangeBalanceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeBalanceRequest) Reset()         { *m = ChangeBalanceRequest{} }
func (m *ChangeBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeBalanceRequest) ProtoMessage()    {}
func (*ChangeBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *ChangeBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeBalanceRequest.Unmarshal(m, b)
}
func (m *ChangeBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeBalanceRequest.Marshal(b, m, deterministic)
}
func (m *ChangeBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeBalanceRequest.Merge(m, src)
}
func (m *ChangeBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeBalanceRequest.Size(m)
}
func (m *ChangeBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeBalanceRequest proto.InternalMessageInfo

func (m *ChangeBalanceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeBalanceRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GetBalanceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(m, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The response message containing the greetings
type AccountReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Balance              int32    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountReply) Reset()         { *m = AccountReply{} }
func (m *AccountReply) String() string { return proto.CompactTextString(m) }
func (*AccountReply) ProtoMessage()    {}
func (*AccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *AccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountReply.Unmarshal(m, b)
}
func (m *AccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountReply.Marshal(b, m, deterministic)
}
func (m *AccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountReply.Merge(m, src)
}
func (m *AccountReply) XXX_Size() int {
	return xxx_messageInfo_AccountReply.Size(m)
}
func (m *AccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountReply proto.InternalMessageInfo

func (m *AccountReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountReply) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type CreateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ChangeBalanceRequest)(nil), "rpc.ChangeBalanceRequest")
	proto.RegisterType((*GetBalanceRequest)(nil), "rpc.GetBalanceRequest")
	proto.RegisterType((*AccountReply)(nil), "rpc.AccountReply")
	proto.RegisterType((*CreateRequest)(nil), "rpc.CreateRequest")
}

func init() {
	proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0)
}

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0xb2,
	0xe3, 0x12, 0x71, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0x75, 0x4a, 0xcc, 0x49, 0xcc, 0x4b, 0x4e, 0x0d,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe3, 0x62, 0x4b, 0xcc, 0x05, 0x69, 0x96, 0x60,
	0x52, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf2, 0x94, 0x94, 0xb9, 0x04, 0xdd, 0x53, 0x4b, 0xf0, 0x6b,
	0x56, 0xb2, 0xe0, 0xe2, 0x71, 0x84, 0x58, 0x1d, 0x94, 0x5a, 0x90, 0x53, 0x89, 0x61, 0xb8, 0x04,
	0x17, 0x7b, 0x12, 0xc4, 0x04, 0xa8, 0xe9, 0x30, 0xae, 0x12, 0x3f, 0x17, 0xaf, 0x73, 0x51, 0x6a,
	0x62, 0x09, 0xcc, 0x68, 0xa3, 0x1d, 0x8c, 0x5c, 0xec, 0x50, 0xb3, 0x84, 0xec, 0xb9, 0x78, 0x51,
	0xdc, 0x2e, 0x24, 0xa9, 0x57, 0x54, 0x90, 0xac, 0x87, 0xcd, 0x3f, 0x52, 0x82, 0x60, 0x29, 0x64,
	0x57, 0x28, 0x31, 0x08, 0x59, 0x72, 0x71, 0x21, 0x1c, 0x2f, 0x24, 0x06, 0x56, 0x82, 0xe1, 0x1b,
	0xec, 0x5a, 0x0d, 0xb9, 0xd8, 0x20, 0x0e, 0x13, 0x12, 0x82, 0x58, 0x8a, 0xec, 0x4a, 0xac, 0x5a,
	0x92, 0xd8, 0xc0, 0xc1, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x79, 0x15, 0xe7, 0x46, 0x87,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// Sends a greeting
	ChangeBalance(ctx context.Context, in *ChangeBalanceRequest, opts ...grpc.CallOption) (*AccountReply, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*AccountReply, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*AccountReply, error)
}

type accountClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountClient(cc grpc.ClientConnInterface) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) ChangeBalance(ctx context.Context, in *ChangeBalanceRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := c.cc.Invoke(ctx, "/rpc.Account/ChangeBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := c.cc.Invoke(ctx, "/rpc.Account/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*AccountReply, error) {
	out := new(AccountReply)
	err := c.cc.Invoke(ctx, "/rpc.Account/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// Sends a greeting
	ChangeBalance(context.Context, *ChangeBalanceRequest) (*AccountReply, error)
	GetBalance(context.Context, *GetBalanceRequest) (*AccountReply, error)
	Create(context.Context, *CreateRequest) (*AccountReply, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) ChangeBalance(ctx context.Context, req *ChangeBalanceRequest) (*AccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeBalance not implemented")
}
func (*UnimplementedAccountServer) GetBalance(ctx context.Context, req *GetBalanceRequest) (*AccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedAccountServer) Create(ctx context.Context, req *CreateRequest) (*AccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_ChangeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ChangeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Account/ChangeBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ChangeBalance(ctx, req.(*ChangeBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Account/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Account/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeBalance",
			Handler:    _Account_ChangeBalance_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Account_GetBalance_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Account_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
